Add spell check to website CI workflow
hashicorp/design-system pull request #1135
Opened 2023-01-25 00:32 UTC by jorytindall

### :pushpin: Summary

This PR adds an additional job to the website CI workflow that runs `cspell` spell check. Pushing this as a test to see if it works.

### :link: External links

Jira ticket: [HDS-1337](https://hashicorp.atlassian.net/browse/HDS-1337)

***

### 👀 Reviewer's checklist:

- [ ] +1 Percy if applicable
- [ ] Confirm that PR has a changelog update via [Changesets](https://github.com/changesets/changesets) if needed

:speech_balloon: Please consider using [conventional comments](https://conventionalcomments.org/) when reviewing this PR.

2023-01-25 14:53 UTC, Dhaulagiri commented
👏  nicely done! The implementation looks good to me.

In order to merge this we'll need to:
* get the failing issues resolved 
* Document and socialize to the team how this change impacts their workflow (i.e. how to fix issues beyond simple spelling mistakes)

2023-01-25 18:49 UTC, jorytindall commented
@Dhaulagiri I fixed the relevant spelling errors and added a section to the wiki in `wiki/Website-Editing-existing-content.md`

2023-01-26 14:02 UTC, MelSumner requested changes
I think a couple of commits accidentally made it into this PR, those will need to be separated out please.

2023-01-26 14:02 UTC, MelSumner commented on website/docs/patterns/button-alignment/partials/overview/overview.md
> +This differentiation is important because the expectations from the user are different in each context. A constrained component or pattern will often be used in an interstitial or circumstantial expe
This page should not be in this PR

2023-01-26 14:02 UTC, MelSumner commented on website/docs/patterns/button-alignment/partials/specifications/order.md
> +- Naturally adheres to our ordering guidelines; button order remains the same except the container is vertical rather than horizontal.
This page should not be in this PR

2023-01-26 14:03 UTC, MelSumner approved these changes
Assuming the page changes are fixes that the spelling tool found, gtg!

2023-01-26 18:57 UTC, merged