New docs website - Post launch / Add inline anchor links for headers
hashicorp/design-system pull request #1167
Opened 2023-02-02 12:02 UTC by didoo

### :pushpin: Summary

This PR, built on top of #1140, adds visible (on hover/focus) anchor links to the headings in the page.

### :hammer_and_wrench: Detailed description

In this PR I have:
- updated logic that handles the generation of the sections TOCs at runtime
    - now we add anchor links to levels H2-H5, but we list only H2-H3 in the sidecar
- applied styling to the injected anchor links

👉 👉 👉 **Preview**: 

@heatherlarsen I looked at the designs in the `website` Figma file, but implementing as they were designed raised some issues that would need to be handled, with some extra complexity, so I decided to go with the common solution (similar to what GitHub does with headings in markdown files).

@MelSumner can you check that the implementation is accessible enough for us?

### :link: External links

Jira ticket: https://hashicorp.atlassian.net/browse/HDS-1221

***

### 👀 Reviewer's checklist:

- [ ] +1 Percy if applicable
- [ ] Confirm that PR has a changelog update via [Changesets](https://github.com/changesets/changesets) if needed

:speech_balloon: Please consider using [conventional comments](https://conventionalcomments.org/) when reviewing this PR.

2023-02-02 16:27 UTC, heatherlarsen commented
@didoo Can you provide more detail about what the issue or concern is with the current designs for this? Or would you rather I set up a sync to discuss? I'm seeing both placement and visual design were not met so hoping we can get a little bit closer to the proposed design before moving forward.

2023-02-06 19:32 UTC, MelSumner requested changes

2023-02-06 19:32 UTC, MelSumner commented on website/app/controllers/show.js
> +const getAnchoredHeadings = (container) => {
[a11y, blocker] links must have discernible text (accessible name) 

(FWIW, this was done incorrectly on the scrappy site too)

2023-02-06 19:32 UTC, MelSumner commented on website/app/styles/pages/application/content.scss
> +  opacity: 0;
[a11y, blocker] Interactive elements cannot be hidden.

2023-02-06 19:51 UTC, MelSumner commented
I think something like this could work re: a11y

```html
<div class="section-title">
  <a href="#section-accessibility" aria-label="accessibility"><span aria-hidden="true">§</span></a>
  <h2 id="section-accessibility">Accessibility</h2>
</div>
```

2023-02-22 22:06 UTC, MelSumner commented
@didoo if you keyboard navigate a components page (I loaded the page, pressed ENTER on the "Skip to content" link, and TAB navigated from there) you will see this: 
![CleanShot 2023-02-22 at 16 02 44](https://user-images.githubusercontent.com/4587451/220770074-00bdc688-ffa9-44c7-a1f3-550c945b038b.png)

2023-02-23 10:30 UTC, didoo commented
> @didoo if you keyboard navigate a components page (I loaded the page, pressed ENTER on the "Skip to content" link, and TAB navigated from there) you will see this: ![CleanShot 2023-02-22 at 16 02 44](https://user-images.githubusercontent.com/4587451/220770074-00bdc688-ffa9-44c7-a1f3-550c945b038b.png)

@MelSumner this is how the browser renders the content, because they're in the DOM, in the `tabpanel`, but with `opacity = 0`. In fact if you change slightly the position you will see this:
<img width="726" alt="screenshot_2402" src="https://user-images.githubusercontent.com/686239/220881208-bcde2757-6c74-43b1-8cc5-0a6536b4f73b.png">
I don't think there's much we can do, unless we change from `opacity=0/1` to `display=none/inline-block`, but in that case I imagine they would not be accessible.

2023-02-23 16:18 UTC, KristinLBradley commented
> > @didoo if you keyboard navigate a components page (I loaded the page, pressed ENTER on the "Skip to content" link, and TAB navigated from there) you will see this
> 
> @MelSumner this is how the browser renders the content, because they're in the DOM, in the `tabpanel`, but with `opacity = 0`. In fact if you change slightly the position you will see this: <img alt="screenshot_2402" width="726" src="https://user-images.githubusercontent.com/686239/220881208-bcde2757-6c74-43b1-8cc5-0a6536b4f73b.png"> I don't think there's much we can do, unless we change from `opacity=0/1` to `display=none/inline-block`, but in that case I imagine they would not be accessible.

@melanie @didoo I think it would help to define the desired expected visual behavior. For example, should the entire Panel have a blue outline when you navigate to it via keyboard? I believe when I was working on HDS Tabs that we didn't want that visual behavior... So maybe we could use HDS Tabs as an example of the desired behavior?

2023-02-23 23:39 UTC, heatherlarsen commented
@KristinLBradley Good call out. I would expect this to behave the same way the HDS `tabs` component behaves, where the first interactive element receives focus, not the whole panel.

2023-03-06 22:20 UTC, MelSumner approved these changes
Noting that it's not the best a11y that interactive elements are hidden, but we've discussed why we are choosing not to do it at this time. 

Otherwise, this seems good to me. the a11y seems to otherwise checkout too. 👍

2023-03-08 19:46 UTC, didoo commented
@heatherlarsen @MelSumner @KristinLBradley I have reverted the second version and polished the first version, which from what I understand from the conversation in Figma is what we want. can you please check it and see if it's OK for you?
https://hds-website-git-post-launch-add-inline-headers-5ce71a-hashicorp.vercel.app/components/alert

some considerations:
- this may not perfect, but is what we can do in our context (other suggested solutions had different DOM structures, essentially based on a parent container that we don't have in our case, so the icon can stay or on the left, or on the right, but not in both places depending on the viewport)
- for the "mobile" viewport, I am hiding the focus outline, because we're likely in a touch environment, so there's no concept of focus (or hover)

> @KristinLBradley Good call out. I would expect this to behave the same way the HDS `tabs` component behaves, where the first interactive element receives focus, not the whole panel.

Yes, this will be done in a distinct ticket/task as follow-up.

/cc @Dhaulagiri

2023-03-09 20:12 UTC, heatherlarsen commented
@didoo I worry about how early we're dropping the visible focus, considering folks may shrink the browser down to place windows side by side. Can we lower that threshold to something more like 414px or 428px ([ref](https://gs.statcounter.com/screen-resolution-stats/mobile/worldwide))? I realize this results in there being no space between the anchor and the heading, but I think that's fine, given we've exhausted all other options. 

Beyond that, I'm ok with this direction from a visual and interaction perspective. I'm not sure how accessible it is though. cc @MelSumner

2023-03-09 20:54 UTC, didoo commented
> @didoo I worry about how early we're dropping the visible focus, considering folks may shrink the browser down to place windows side by side. Can we lower that threshold to something more like 414px or 428px ([ref](https://gs.statcounter.com/screen-resolution-stats/mobile/worldwide))? I realize this results in there being no space between the anchor and the heading, but I think that's fine, given we've exhausted all other options.

@heatherlarsen I'm dropping the visible focus when the padding on the sides of the content goes from `24px` to `16px` otherwise, this happens:

![localhost_3001_components_alert](https://user-images.githubusercontent.com/686239/224155361-545fd7d7-e602-4a41-8719-bf9bd781e5bf.png)

Let me know if that's OK for you, in which case I can always leave the focus visible, even on small screens.

2023-03-09 21:25 UTC, heatherlarsen commented
@didoo Yup, all good. Let's just keep it visible for all sizes, then.

2023-03-09 22:57 UTC, MelSumner approved these changes

2023-03-10 08:32 UTC, merged