Add loading state on search input
hashicorp/design-system pull request #1452
Opened 2023-06-27 15:37 UTC by alex-ju

### :pushpin: Summary

Add `@isLoading` on `<TextInput @type="search"/>`

### :hammer_and_wrench: Detailed description

When a search operation does not happen instantly it is often helpful to reflect the loading state in the search input.

We're introducing the `@isLoading` argument on `<TextInput @type="search"/>` to replace the magnifying glass with a loading spinner to be used while fetching the results in a search operation.

Note: we traditionally apply the animation to the loading icon via CSS, but in the current implementation, the magnifying glass is a background image on the `<input>` element, so it wouldn't work. For this reason, we create an SVG animation.

### :camera_flash: Screenshots

### :link: External links

Jira ticket: [HDS-2116](https://hashicorp.atlassian.net/browse/HDS-2116)

***

### 👀 Reviewer's checklist:

- [ ] +1 Percy if applicable
- [ ] Confirm that PR has a changelog update via [Changesets](https://github.com/changesets/changesets) if needed

:speech_balloon: Please consider using [conventional comments](https://conventionalcomments.org/) when reviewing this PR.

2023-06-28 01:06 UTC, cveigt requested changes
This looks great, Alex. Thanks for making these updates. I only have a piece of feedback. Can we change the color of the `loading` icon to match the `search` icon? It should be foreground faint (or the equivalent on the form tokens)

2023-06-28 08:03 UTC, alex-ju commented
> This looks great, Alex. Thanks for making these updates. I only have a piece of feedback. Can we change the color of the `loading` icon to match the `search` icon? It should be foreground faint (or the equivalent on the form tokens)

Thanks for the review, Christian! Updated now to use foreground faint

2023-06-28 08:28 UTC, didoo approved these changes
All good for me. Left only minor comments/suggestions.

2023-06-28 08:28 UTC, didoo commented on .changeset/bright-cougars-dress.md
> +Add loading state on search input
I think we should start to do something like this for our changelogs to they're easer to visually scan/parse (look at [last release](https://github.com/hashicorp/design-system/releases/tag/%40hashicorp%2Fdesign-system-components%402.7.1) to see what I mean)

```suggestion
`Form::TextInput` - Add loading state on "search" type
```

2023-06-28 08:28 UTC, didoo commented on .changeset/tricky-badgers-try.md
> +Add design token for loading state on search input
```suggestion
Add design token for loading state icon on search input
```

2023-06-29 05:11 UTC, cveigt approved these changes

2023-06-29 07:23 UTC, merged