Export `utils` functions as default
hashicorp/design-system pull request #1530
Opened 2023-07-27 11:20 UTC by alex-ju

### :pushpin: Summary

Export `utils` functions as default

### :hammer_and_wrench: Detailed description

I feel like there are two avenues here, export the utils function as default, or remove the `app/utils` files – I went for the first option, but happy to reconsider.

### :link: External links

Jira ticket: [HDS-2275](https://hashicorp.atlassian.net/browse/HDS-2275)

***

### 👀 Reviewer's checklist:

- [ ] +1 Percy if applicable
- [ ] Confirm that PR has a changelog update via [Changesets](https://github.com/changesets/changesets) if needed
- [ ] Confirm that A11y tests have been run locally for this component

:speech_balloon: Please consider using [conventional comments](https://conventionalcomments.org/) when reviewing this PR.

2023-07-27 12:30 UTC, didoo reviewed
Have it been tested in a consumer? (I am asking because my understanding is that these almost-empty duplicate files are needed by Ember because our components code is an addon, and so they are needed at compilation time.

2023-07-27 13:03 UTC, MelSumner requested changes
I think these need to stay here. Any specific reason to remove them other than the warnings? 

Also what is the warning? Is it something we need to address?

2023-07-28 08:54 UTC, alex-ju commented
> Have it been tested in a consumer?

No, I have not – I tried yesterday but setting up `cloud-ui` to use embroider is not trivial. However, I am confident about the export/import mechanism we are altering in this PR. Alternatively, we can potentially ask the consumer to test the 'solution' (@aklkv do you think you would have time to review this change at some point?).

> (I am asking because my understanding is that these almost-empty duplicate files are needed by Ember because our components code is an addon, and so they are needed at compilation time.

> I think these need to stay here. Any specific reason to remove them other than the warnings?

@didoo @MelSumner my understanding is that these `app/*/*.js` files are required for consumers to be able to discover our components and helpers – basically, these exports constitute our add-on API. Our intention is to only use these functions internally and not make them part of the API so I consider removing the exports is the best way forward.

> Also what is the warning? Is it something we need to address?

The warnings complain that we're trying to expose these two utility functions in `app/utils/*.js`, but we're not exporting defaults `addon/utils/*.js`. I copied the warnings from the Jira card to the PR description.

2023-07-29 09:06 UTC, aklkv commented
@alex-ju Thank you for addressing this 🙏🏻 I have a branch with working embroider for cloud-ui I can test this change on it. Also I have confirm that everything that is in `app/` is a public API of the addon, if something is used only internally it should not have re export file. Also it is default behaviour of ember-cli to create this file when generating things like utils. we had to remove very large number of useless pre-exports from cloud-ui as well. @MelSumner you are absolutely correct in saying that it's just a warning and it doesn't break anything but why keep it if we don't need it and makes build output for consumer that much cleaner.

2023-08-02 13:13 UTC, didoo approved these changes

2023-08-03 19:37 UTC, MelSumner approved these changes
I still think we should fix the root cause instead of removing these files but I won't block on it.

2023-08-07 10:05 UTC, merged