`Alert` and `Toast` Overview Update
hashicorp/design-system pull request #1720
Opened 2023-10-13 19:23 UTC by andgen404

### :pushpin: Summary

`Alert` and `Toast` - Changed the overview section for both components to have a bit more clarity on when to use. 

### :link: External links

Jira ticket: [HDS-2441](https://hashicorp.atlassian.net/browse/HDS-2441)

***

### 👀 Component checklist

- [ ] Percy was checked for any visual regression
- [ ] A11y tests have been run locally (`yarn test:a11y --filter="COMPONENT-NAME"`)
- [ ] If documenting a new component, an acceptance test that includes the `a11yAudit` has been added
- [ ] A changelog entry was added via [Changesets](https://github.com/changesets/changesets) if needed

:speech_balloon: Please consider using [conventional comments](https://conventionalcomments.org/) when reviewing this PR.

2023-10-16 20:47 UTC, heatherlarsen requested changes
Great first try at updating the docs! I'm not sure they get to the root of the issue outlined in the Jira ticket, though, so I left a few comments to address that further. 

A few other ideas we discussed earlier for the `Alert` page include:

- move the "Usage" section above the "Types of alerts" section
- update the sentence "To communicate feedback on a user’s action..." to "To communicate successful feedback on a user’s action..."

2023-10-16 20:47 UTC, heatherlarsen commented on website/docs/components/alert/partials/guidelines/overview.md
> +Alerts display brief but important system-generated messages and capture the user's attention without interrupting their workflow. They excel in conveying crucial information or errors, such as valid
```suggestion
Alerts display brief but important messages that capture the user's attention but don't interrupt their workflow. 
```

Per our discussion this morning, this content is better suited for the "Critical alerts" section between the heading and the first "do" block.

> Use critical alerts to convey crucial information or errors, such as validation errors requiring user action.

2023-10-16 20:47 UTC, heatherlarsen commented on website/docs/components/toast/partials/guidelines/overview.md
> +Toasts deliver messages resulting from a user's actions. They typically disappear after a set interval or upon user dismissal, offering a non-intrusive way to provide feedback. While [Alerts](/compon
Providing feedback based on our earlier conversation. I removed the second half of this section to:

1. reduce confusion around terms such as "system-generated"
2. remove duplicative information (info is also presented in the when to use/when not to use section)

```suggestion
Toasts deliver messages to communicate an ongoing process or as a result of a user's actions. They typically disappear after a set interval or upon user dismissal, offering a non-intrusive way to provide feedback. 
```

2023-10-16 21:58 UTC, andgen404 commented on website/docs/components/alert/partials/guidelines/overview.md
> +Alerts display brief but important messages that capture the user's attention but don't interrupt their workflow.
```suggestion
Alerts display brief but important messages that capture the user's attention but doesn't interrupt their workflow. 
```

2023-10-17 15:30 UTC, heatherlarsen commented on website/docs/components/alert/partials/guidelines/guidelines.md
> +Use compact alerts when a less prominent alert is needed.
@MelSumner This is current content on the website, and changing it is out of the scope of the ticket. I asked Andrew to re-organize some of the content (moving the "Usage" section to the top), which is in scope.

2023-10-19 19:00 UTC, andgen404 commented on website/docs/components/alert/partials/guidelines/guidelines.md
> +- For subtle feedback on a user’s action, consider [Toast](/components/toast).
```suggestion
- To communicate successful feedback on a user’s action, consider [Toast](/components/toast).
```

2023-10-19 19:50 UTC, jorytindall commented on website/docs/components/toast/partials/guidelines/overview.md
> +Toasts deliver messages to communicate an ongoing process or as a result of a user's actions. They typically disappear after a set interval or upon user dismissal, offering a non-intrusive way to pro
```suggestion
Toasts deliver messages to communicate an ongoing process or result of a user action. They typically disappear after a set interval or upon user dismissal, offering a non-intrusive way to provide feedback. 
```

2023-10-20 23:27 UTC, heatherlarsen commented on website/docs/components/toast/partials/guidelines/overview.md
> +Toasts deliver messages to communicate an ongoing process or result of a user action. They typically disappear after a set interval or upon user dismissal, offering a non-intrusive way to provide fee
Slight change to communicate that toasts may not always be the right component to communicate a result of a user action. wdyt?

```suggestion
Toasts deliver messages to communicate an ongoing process or, sometimes, a result of a user action. They typically disappear after a set interval or upon user dismissal, offering a non-intrusive way to provide feedback. 
```

2023-10-20 23:49 UTC, heatherlarsen approved these changes
Thanks for making those adjustments!

2023-10-23 12:56 UTC, alex-ju approved these changes

2023-10-23 22:40 UTC, merged