copy-item icon size
hashicorp/design-system pull request #247
Opened 2022-04-26 15:44 UTC by MelSumner

Resolves issue where the `copy-item` icon was too small when text was super long. 

(I wonder if it would make more sense for @didoo to pull the relevant code lines into his most recent PR set? Leaving this in draft state for that reason)

Screenshot showing that the icon no longer shrinks:
![CleanShot 2022-04-26 at 10 38 12](https://user-images.githubusercontent.com/4587451/165339272-59bf165a-8351-4c89-91fe-b1c04169b445.png)

2022-04-26 17:39 UTC, didoo requested changes
See my comments.

2022-04-26 17:39 UTC, didoo commented on packages/components/app/styles/components/dropdown.scss
> +    flex: 1 0 0;
You don't need this.
```suggestion
```

2022-04-26 17:43 UTC, didoo commented
> (I wonder if it would make more sense for @didoo to pull the relevant code lines into his most recent PR set? Leaving this in draft state for that reason)

The best thing would be to PR against the "feature branch" `dropdown-finalize-implementation` (see https://github.com/hashicorp/design-system/pull/200). The problem I suspect is that if you do it now, editing this PR, it will have very complex conflicts. So my suggestion is:
- delete your local `melsumner/copy-item-icon-fix` branch (but don't push!)
- branch from `dropdown-finalize-implementation` using the same name (`melsumner/copy-item-icon-fix`)
- make the changes in this new branch (it's 3 lines to change)
- force push the newly created branch `melsumner/copy-item-icon-fix`
- this will overwrite the commits in this PR
- edit this PR and make it point against `dropdown-finalize-implementation`

2022-04-27 17:14 UTC, MelSumner commented
Closed in favor of #253

2022-04-27 17:14 UTC, closed without merging