resolves FF bug by using their recommended approach
hashicorp/design-system pull request #334
Opened 2022-06-01 22:53 UTC by MelSumner

### :pushpin: Summary

If merged, this PR should resolve issue #290 

### :hammer_and_wrench: Detailed description

I can't quite get the conditional to activate correctly in Firefox, so I ended up taking out the clipboard API and just using Firefox's recommended approach. I tested it in Chrome, FF and Safari and it's working as expected. 

Here's what I wanted to do though, maybe someone can see what I am missing: 

```js
@action
  async copyCode() {
    // check to see if the browser even supports the clipboard-write permission
    if (navigator.permissions.query({ name: 'clipboard-write' })) {
      // query for the clipboard-write navigator permission
      const permResult = await navigator.permissions.query({
        name: 'clipboard-write',
      });

      // if the permission is granted, then we can copy the text
      if (permResult.state === 'granted' || permResult.state === 'prompt') {
        // https://developer.mozilla.org/en-US/docs/Web/API/Clipboard
        await navigator.clipboard.writeText(this.args.text);
        const result = await navigator.clipboard.readText();

        // if the copied text is equal to the text to be copied, then we have been successful
        if (result === this.args.text) {
          this.isSuccess = true;
          console.log(`result is ${result}`);

          // make it fade back to the default state
          setTimeout(() => {
            this.isSuccess = false;
          }, 1000);
        }
      } else {
        // if permission is denied, we want to know about it
        console.log(`Permission denied: ${permResult.state}`);
        alert(
          'you have not granted your browser permission to use the clipboard'
        );
      }
    } else {
      // if the clipboard-write permission doesn't exist for the browser, we want to try something else
      let copyText = await this.args.text;
      // https://codepen.io/chrisdavidmills/full/gzYjag/
      // execCommand is supposedly deprecated but it's also what Firefox says to do in this situation so we'll try it
      await document.execCommand('copy', false, copyText || '');

      console.log(`Copied text: ${copyText}`);

      if (copyText === this.args.text) {
        this.isSuccess = true;
        console.log(`copied text is ${copyText}`);

        // make it fade back to the default state
        setTimeout(() => {
          this.isSuccess = false;
        }, 1000);
      }
    }
  }
  ```

### 👀 How to review

👉 Review by files changed

Reviewer's checklist:

- [ ] +1 Percy if applicable
- [ ] Confirm that PR has a changelog update via [Changesets](https://github.com/changesets/changesets) if needed

:speech_balloon: Please consider using [conventional comments](https://conventionalcomments.org/) when reviewing this PR.

2022-06-02 20:59 UTC, Dhaulagiri reviewed
This seems sufficient to me to unblock this. 

Can you add a changeset for this so it gets included in a release?

2022-06-02 20:59 UTC, Dhaulagiri commented on packages/components/addon/components/hds/dropdown/list-item/copy-item.js
> +    let copyText = await this.args.text;
i don't think this is asynchronous

```suggestion
    let copyText = this.args.text;
```

2022-06-02 20:59 UTC, Dhaulagiri commented on packages/components/addon/components/hds/dropdown/list-item/copy-item.js
> +    let copyText = await this.args.text;
i don't think this is asynchronous

```suggestion
    let copyText = this.args.text;
```

2022-06-02 20:59 UTC, Dhaulagiri commented on packages/components/addon/components/hds/dropdown/list-item/copy-item.js
> +      // console.log(`success: ${this.isSuccess}; copied text: ${copyText}`);
[suggestion] i generally try to not to leave behind debugging statements, so I think this and the line above could be removed

2022-06-02 20:59 UTC, Dhaulagiri commented on packages/components/addon/components/hds/dropdown/list-item/copy-item.js
> +      // console.log(`success: ${this.isSuccess}; copied text: ${copyText}`);
[suggestion] i generally try to not to leave behind debugging statements, so I think this and the line above could be removed

2022-06-06 10:41 UTC, didoo commented on packages/components/addon/components/hds/dropdown/list-item/copy-item.js
> +    let copyText = await this.args.text;
+1

2022-06-06 11:02 UTC, didoo requested changes
@MelSumner a few points:
- I tested the feature in Chrome and Safari and it doesn't work for me
- the issue with Firefox was with the _read_ part (`navigator.clipboard.readText`) not the _write_ part; with the solution proposed in this PR we're not reading at all the clipboard, so at that point we could have just used the old/existing code and remove (or even better conditionally test) the `navigator.clipboard.readText`

Let me know if you prefer to pair on this, ok?

2022-06-07 15:16 UTC, closed without merging